name: haskell-debug-adapter
version: '0.0.29.0'
synopsis: Haskell Debug Adapter.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2016-2019 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/haskell-debug-adapter/
bug-reports: https://github.com/phoityne/haskell-debug-adapter/issues

extra-source-files:
- README.md
- Changelog.md

ghc-options:
- -threaded
- -rtsopts
- -with-rtsopts=-N
- -Wall
- -Werror
- -fno-warn-unused-do-bind
- -fno-warn-name-shadowing
- -fno-warn-orphans
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

default-extensions:
- AutoDeriveTypeable
- BangPatterns
- BinaryLiterals
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveDataTypeable
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DoAndIfThenElse
- EmptyDataDecls
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- InstanceSigs
- KindSignatures
- LambdaCase
- MonadFailDesugaring
- MultiParamTypeClasses
- MultiWayIf
- NamedFieldPuns
- OverloadedLabels
- PartialTypeSignatures
- PatternGuards
- PolyKinds
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TupleSections
- TypeFamilies
- TypeOperators
- TypeSynonymInstances
- ViewPatterns

when:
- condition: impl(ghc < 8.4.0)
  dependencies: unsupported-ghc-version > 1 && < 1

dependencies:
- base >=4.7 && <5
- mtl
- hslogger
- text
- bytestring
- MissingH
- conduit
- conduit-extra
- resourcet
- lens
- safe-exceptions
- aeson
- data-default
- containers
- parsec
- async
- directory
- filepath
- process
- Cabal
- clock
- fsnotify
- cmdargs
- haskell-dap >=0.0.11.0

library:
  source-dirs: src
  exposed-modules:
  - Haskell.Debug.Adapter.Control
  
executables:
  haskell-debug-adapter:
    main: Main.hs
    source-dirs: app
    dependencies:
    - haskell-debug-adapter

tests:
  haskell-debug-adapter-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - hspec
    - haskell-debug-adapter

