@startuml 101_deploy
skinparam defaultFontName MS Gothic
'skinparam minClassWidth 100
'skinparam minClassHeight 400
skinparam monochrome true
'skinparam monochrome reverse
'skinparam linetype polyline
skinparam linetype ortho
'skinparam linetype splines
skinparam arrowThickness 2
' left to right direction

title <size:18>Haskell Debugging System Deployment Diagram</size>

node "VSCode" {
  component "phoityne-vscode" <<extension>>
}


node "Vim/NeoVim" {
  component "hdx4vim" <<config>>
}

node "Emacs" {
  component "hdx4emacs" <<config>>
}

node "Visual Studio" {
  component "hdx4vs" <<extension>>
}

node "Haskell Debugger" {
  component "haskell-dap" <<library>>
  component "haskell-debug-adapter" <<executable>>
  rectangle ghci #line.dashed {
    component "ghci-dap" <<executable>>
  }
}

[phoityne-vscode] -- [haskell-debug-adapter] : <<DAP>>
[hdx4vim] -- [haskell-debug-adapter] : <<DAP>>
[hdx4emacs] -- [haskell-debug-adapter] : <<DAP>>
[hdx4vs] -- [haskell-debug-adapter] : <<DAP>>
[haskell-debug-adapter] -- [ghci-dap] : <<stdio>>
[haskell-debug-adapter] --> [haskell-dap] : <<use>>
[ghci-dap] -l-> [haskell-dap] : <<use>>

@enduml
