@startuml 101_deploy
skinparam defaultFontName MS Gothic
'skinparam minClassWidth 100
'skinparam minClassHeight 400
skinparam monochrome true
'skinparam monochrome reverse
'skinparam linetype polyline
skinparam linetype ortho
'skinparam linetype splines
skinparam arrowThickness 2
left to right direction

title <size:18>Haskell Debugging System Deployment Diagram</size>

node "VSCODE" {
  component "phoityne-vscode" <<extension>>
}

node "Haskell Debugger" {
  component "haskell-dap" <<library>>
  component "hda" <<process>>
  rectangle ghci #line.dashed {
    component "ghci-dap" <<process>>
  }
}

[phoityne-vscode] -- [hda] : <<stdio>>
[hda] --> [ghci-dap] : <<stdio>>
[hda] -l-> [haskell-dap] : <<use>>
[ghci-dap] -l-> [haskell-dap] : <<use>>

note left of "phoityne-vscode"
  hda4vsc
end note

@enduml
